### ISSUE TITLE
[Repo Cleanup] What themes will get used?

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-extra#7]
This is more a question towards the desktop image maintainers.

What themes do we need to support? What DE's should we maintain images for?
Themes in question are:
* artwork-breath (Breath theme)
* artwork-maia (Maia theme)
* vertex-maia-themes (Vertex Maia theme)
* vertex-themes (Vertex theme)

The themes no one wants to maintain will get removed from the repository.

**Comment by commonsourcecs** [comment]
If I am not mistaken, maia is the oldest of those, and I am not sure it is even gtk 3.2+ ready. 
So that would be on the chopping block in my opinion - but I do not entirely know the state of the others. I had made some basic fixes to breath and ported it to gtk in the past, but havent looked at it since. 
Most likely on my own rig I would opt for a breath-styled numix pretty quick. 
(using oomox/numix-folders to edit the base numix)
For the DE's we are looking at I do believe one obvious choice would be XFCE, possibly followed by lxqt.
This is just my quick spitball - I'm not determined about any of it really.

**Comment by GrayJack** [comment]
For the themes I suppose we should stick with the most recent, probably breath

For DE I like Mate/XFCE/LXQt, all those are quite lightweight for those ARM dev boards

**Comment by dodgejcr** [comment]
I agree with the previous comments. Keep the latest, kill the rest. If they are requested, we could always add them back with an expected maintainer to keep track of the PKGBUILD inside of the community repo.

If we decide to actually maintain desktop images (I assume you mean a release preloaded with an environment like the previous base edition) I vote for XFCE and possibly LXQt. One gtk, one qt. Both are stable and provide plenty of features for the majority of users. Like before, others can be added via community editions.

If we decide to go a different route (@Strit the thing with chrys [dont know if this is public]) this may all become moot which is the desired behavior however, it will add a few more 'maintainer' jobs to people or add new people to help. Even still, probably best to do the two as Official and then others as community

**Comment by Strit** [comment]
I agree.
I'll remove all themes except Breath later this week I think. Maybe tomorrow or tonight.

**Comment by Strit** [comment]
I removed all themes but Breath.

Of you need other themes for your images. Please add them, and let me know so I can add them to the build server and repo.
